services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # mounting config file
      - prometheus-data:/prometheus # mounting db for persistent data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' # config location
      - '--storage.tsdb.path=/prometheus' # db location
      - '--storage.tsdb.retention.time=30d' # data retention time
    networks:
      - homelab-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD} # sets admin password, change on login
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER} # Sets admin username
      - GF_INSTALL_PLUGINS=grafana-piechart-panel # Installs pie chart plugin for dashboards
    volumes:
      - grafana-data:/var/lib/grafana # volume for grafana dashboards and data
    depends_on:
      - prometheus # tells docker to start prometheus before this
    networks:
      - homelab-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      # Mounts the host's /proc filesystem (contains CPU, memory, process info) as read-only into container
      - /proc:/host/proc:ro
      # Mounts the host's /sys filesystem (hardware/kernel info) as read-only
      - /sys:/host/sys:ro
      # Mounts the entire host filesystem as read-only 
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc' # where to find proc data
      - '--path.sysfs=/host/sys' # where to find sys data
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)' # ignore specific directories
    networks:
      - homelab-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro # Root filesystem
      - /var/run:/var/run:ro # Docker socket and runtime info
      - /sys:/sys:ro # file sys/hardware info 
      - /var/lib/docker/:/var/lib/docker:ro # Docker's internal data
      - /dev/disk/:/dev/disk:ro # Disk device information
    privileged: true # Grants the container elevated permissions to access kernel-level Docker and system metrics
    networks:
      - homelab-network
# This defines named volumes that Docker manages
volumes:
  prometheus-data:
  grafana-data:

networks:
  homelab-network:
    external: true
